[package]
org = "uvindra"
name = "consumer"
version = "0.1.0"
distribution = "2201.7.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "pact_wrapper"
version = "0.1.0"
repository = "local"