[package]
org = "uvindra"
name = "pact_wrapper"
version = "0.1.0"
distribution = "2201.7.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "./javalibs/consumer-4.5.9.jar"

[[platform.java11.dependency]]
path = "./javalibs/model-4.5.9.jar"
