[package]
org = "ballerinax"
name = "pact_wrapper"
version = "0.1.0"
distribution = "2201.7.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "./javalibs/consumer-4.5.9.jar"

[[platform.java11.dependency]]
path = "./javalibs/model-4.5.9.jar"


[[platform.java11.dependency]]
path = "./javalibs/matchers-4.5.9.jar"


[[platform.java11.dependency]]
path = "./javalibs/support-4.5.9.jar"

[[platform.java11.dependency]]
groupId = "org.apache.httpcomponents.core5"
artifactId = "httpcore5"
version = "5.2.3"

[[platform.java11.dependency]]
groupId = "org.apache.httpcomponents.client5"
artifactId = "httpclient5"
version = "5.2.1"


[[platform.java11.dependency]]
groupId = "org.apache.httpcomponents.client5"
artifactId = "httpclient5-fluent"
version = "5.2.1"


[[platform.java11.dependency]]
groupId = "com.googlecode.java-diff-utils"
artifactId = "diffutils"
version = "1.3.0"

[[platform.java11.dependency]]
groupId = "dk.brics.automaton"
artifactId = "automaton"
version = "1.11-8"

[[platform.java11.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.75.Final"

[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "2.0.0-alpha1"

[[platform.java11.dependency]]
groupId = "io.ktor"
artifactId = "ktor-server-netty"
version="2.3.0"

[[platform.java11.dependency]]
groupId = "io.ktor"
artifactId = "ktor-network-tls-certificates"
version="2.3.0"

[[platform.java11.dependency]]
groupId = "io.pact.plugin.driver"
artifactId = "core"
version="0.4.1"


[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-lang3"
version = "3.12.0"

[[platform.java11.dependency]]
groupId = "com.github.mifmif"
artifactId = "generex"
version = "1.0.2"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-io"
version = "1.3.2"

[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-text"
version = "1.10.0"

[[platform.java11.dependency]]
groupId = "org.apache.tika"
artifactId = "tika-core"
version="2.8.0"


[[platform.java11.dependency]]
groupId = "org.hamcrest"
artifactId = "hamcrest"
version = "2.2"

[[platform.java11.dependency]]
groupId = "org.spockframework"
artifactId = "spock-core"
version = "2.3-groovy-4.0"

[[platform.java11.dependency]]
groupId = "junit"
artifactId = "junit"
version="4.13.2"

[[platform.java11.dependency]]
groupId = "ch.qos.logback"
artifactId = "logback-classic"
version = "1.2.6"

[[platform.java11.dependency]]
groupId = "org.cthul"
artifactId = "cthul-matchers"
version = "1.1.0"

[[platform.java11.dependency]]
groupId = "org.apache.groovy"
artifactId = "groovy"
version="4.0.15"

[[platform.java11.dependency]]
groupId = "org.apache.groovy"
artifactId = "groovy-json"
version="4.0.15"

[[platform.java11.dependency]]
groupId = "org.apache.groovy"
artifactId = "groovy-xml"
version="4.0.15"

[[platform.java11.dependency]]
groupId = "org.apache.groovy"
artifactId = "groovy-dateutil"
version="4.0.15"

[[platform.java11.dependency]]
groupId = "net.bytebuddy"
artifactId = "byte-buddy"
version = "1.10.22"

[[platform.java11.dependency]]
groupId = "org.objenesis"
artifactId = "objenesis"
version = "3.2"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.13.4"

[[platform.java11.dependency]]
groupId = "io.grpc"
artifactId = "grpc-protobuf"
version = "1.45.1"

[[platform.java11.dependency]]
groupId = "org.junit.jupiter"
artifactId = "junit-jupiter-api"
version = "5.8.0"

[[platform.java11.dependency]]
groupId = "io.github.oshai"
artifactId = "kotlin-logging-jvm"
version = "5.1.0"

[[platform.java11.dependency]]
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-stdlib"
version="1.9.10"

[[platform.java11.dependency]]
groupId = "org.json"
artifactId = "json"
version="20230227"
